### ISSUE TITLE
run time error

### ISSUE THREAD

**Issue by wolfgangabersdorf** [frankandrobot/FFvideoLiveWallpaper#2]
03-11 06:47:42.644: E/AndroidRuntime(332): java.lang.RuntimeException: Unable to instantiate service ffvideolivewallpaper.frankandrobot.com.VideoLiveWallpaper: java.lang.ClassNotFoundException: ffvideolivewallpaper.frankandrobot.com.VideoLiveWallpaper in loader dalvik.system.PathClassLoader[/data/app/ffvideolivewallpaper.frankandrobot.com-2.apk]
03-11 06:47:42.644: E/AndroidRuntime(332):     at android.app.ActivityThread.handleCreateService(ActivityThread.java:2943)
03-11 06:47:42.644: E/AndroidRuntime(332):     at android.app.ActivityThread.access$3300(ActivityThread.java:125)
03-11 06:47:42.644: E/AndroidRuntime(332):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2087)
03-11 06:47:42.644: E/AndroidRuntime(332):     at android.os.Handler.dispatchMessage(Handler.java:99)
03-11 06:47:42.644: E/AndroidRuntime(332):     at android.os.Looper.loop(Looper.java:123)
03-11 06:47:42.644: E/AndroidRuntime(332):     at android.app.ActivityThread.main(ActivityThread.java:4627)
03-11 06:47:42.644: E/AndroidRuntime(332):     at java.lang.reflect.Method.invokeNative(Native Method)
03-11 06:47:42.644: E/AndroidRuntime(332):     at java.lang.reflect.Method.invoke(Method.java:521)
03-11 06:47:42.644: E/AndroidRuntime(332):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
03-11 06:47:42.644: E/AndroidRuntime(332):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
03-11 06:47:42.644: E/AndroidRuntime(332):     at dalvik.system.NativeStart.main(Native Method)
03-11 06:47:42.644: E/AndroidRuntime(332): Caused by: java.lang.ClassNotFoundException: ffvideolivewallpaper.frankandrobot.com.VideoLiveWallpaper in loader dalvik.system.PathClassLoader[/data/app/ffvideolivewallpaper.frankandrobot.com-2.apk]
03-11 06:47:42.644: E/AndroidRuntime(332):     at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:243)
03-11 06:47:42.644: E/AndroidRuntime(332):     at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
03-11 06:47:42.644: E/AndroidRuntime(332):     at java.lang.ClassLoader.loadClass(ClassLoader.java:532)
03-11 06:47:42.644: E/AndroidRuntime(332):     at android.app.ActivityThread.handleCreateService(ActivityThread.java:2940)

**Comment by ravenfeld** [comment]
I have the same error, have you result this problem ?

thank you

**Comment by raza1721** [comment]
No .not solved

Date: Tue, 27 Aug 2013 02:54:02 -0700

**Comment by ravenfeld** [comment]
And have you use other source ?

**Comment by raza1721** [comment]
still not done
.

Date: Thu, 29 Aug 2013 07:06:03 -0700

**Comment by jacquesgiraudel** [comment]
Try to check the GLWallpaperService.jar in Order and export (Eclipse)

**Comment by shivanivasundhara** [comment]
hello..I am using  your .so files.There are only 2 folders given.I am getting error message on runtime

>  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ffvideolivewallpaper.frankandrobot.com-1/base.apk"],nativeLibraryDirectories=[/data/app/ffvideolivewallpaper.frankandrobot.com-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libavcore.so"
                                                                                            at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                                            at java.lang.System.loadLibrary(System.java:988)
                                                                                            at ffvideolivewallpaper.frankandrobot.com.NativeCalls.<clinit>(NativeCalls.java:63)
                                                                                            at ffvideolivewallpaper.frankandrobot.com.VideoLiveWallpaper.onSharedPreferenceChanged(VideoLiveWallpaper.java:165)
                                                                                            at ffvideolivewallpaper.frankandrobot.com.VideoLiveWallpaper.onCreate(VideoLiveWallpaper.java:99)
                                                                                            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2782)
                                                                                            at android.app.ActivityThread.access$1800(ActivityThread.java:154)
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5290)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
