### ISSUE TITLE
Package change issue..

### ISSUE THREAD

**Issue by AlobhaTechnologies** [frankandrobot/FFvideoLiveWallpaper#4]
Hi,

I am changing the java class package and manifest package entry facing issue:

01-17 01:19:34.281: E/AndroidRuntime(26750): java.lang.ExceptionInInitializerError
01-17 01:19:34.281: E/AndroidRuntime(26750):    at com.alobha.davidmedlock.VideoLiveWallpaper.onSharedPreferenceChanged(VideoLiveWallpaper.java:133)
01-17 01:19:34.281: E/AndroidRuntime(26750):    at com.alobha.davidmedlock.VideoLiveWallpaper.onCreate(VideoLiveWallpaper.java:67)
01-17 01:19:34.281: E/AndroidRuntime(26750):    at android.app.ActivityThread.handleCreateService(ActivityThread.java:2383)
01-17 01:19:34.281: E/AndroidRuntime(26750):    at android.app.ActivityThread.access$1600(ActivityThread.java:137)
01-17 01:19:34.281: E/AndroidRuntime(26750):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1288)
01-17 01:19:34.281: E/AndroidRuntime(26750):    at android.os.Handler.dispatchMessage(Handler.java:99)
01-17 01:19:34.281: E/AndroidRuntime(26750):    at android.os.Looper.loop(Looper.java:213)
01-17 01:19:34.281: E/AndroidRuntime(26750):    at android.app.ActivityThread.main(ActivityThread.java:4793)
01-17 01:19:34.281: E/AndroidRuntime(26750):    at java.lang.reflect.Method.invokeNative(Native Method)
01-17 01:19:34.281: E/AndroidRuntime(26750):    at java.lang.reflect.Method.invoke(Method.java:511)
01-17 01:19:34.281: E/AndroidRuntime(26750):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
01-17 01:19:34.281: E/AndroidRuntime(26750):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
01-17 01:19:34.281: E/AndroidRuntime(26750):    at dalvik.system.NativeStart.main(Native Method)
01-17 01:19:34.281: E/AndroidRuntime(26750): Caused by: java.lang.UnsatisfiedLinkError: Couldn't load avcore: findLibrary returned null

With existing package it's working fine, but after changing the package facing this issue.

Please help me, help will be appreciated

Regards,
Naveen

**Comment by jacquesgiraudel** [comment]
You have to change the method signatures in the c program (video.c). 
eg : Java_ffvideolivewallpaper_frankandrobot_com_NativeCalls_initVideo follow the package structure of the method.
